=== VeraAceves/examenFinal/Tema 5/XSLT/Ejercicios Adicionales/508.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="inventario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="producto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="peso">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="unidad" use="required" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="lugar">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="aula" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="edificio" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="codigo" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== VeraAceves/examenFinal/Tema 5/XSLT/Ejercicios Adicionales/508.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="508.xsl"?>
<inventario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="508.xsd">
    <producto codigo="P1">
        <peso unidad="kg">10</peso>
        <nombre>Ordenador</nombre>
        <lugar edificio="B">
            <aula>10</aula>
        </lugar>
    </producto>
    <producto codigo="P2">
        <peso unidad="g">500</peso>
        <nombre>Switch</nombre>
        <lugar edificio="A">
            <aula>6</aula>
        </lugar>
    </producto>
</inventario>
